### PR TITLE
change blockchange Foundation visualization type to 'Text'

### PR DESCRIPTION
**Pull request by nam20485**
Addresses #117

### CODE REVIEW

**Comment by nam20485** [comment]
Need this merged to master so it is deployed to production.

**Comment by nam20485** [comment]
I'm not actually sure what to test when writing a unit test for this- I don't know what this functionality does. I changes the visualization type to "Text" form whatever the default is when no visualization type is specified. That is the sum total of my knowledge about this code area and my change.

@mendozaline you advised to make this change- do you know what should be tested?

**Comment by mendozaline** [comment]
Currently if you click on the Change in Ridership by Census Block foundation layer in the Sandbox the dashboard will not pop up. This is because there's no visualization type set. 

With this change, when you click on one of the polygons the dashboard should pop up and show the text "Ridership Change from 2009 to 2017" and the percent change for that Census block. That's the extent of the change.

**Comment by nam20485** [comment]
This is deployed to production but I don't see anything popping up. But I am not sure what polygon shapes I am supposed to be activating by clicking.

**Comment by mendozaline** [comment]
That's because the value for `slide_meta.attributes.primary.field` is "pct_change" and the value in `properties` is "stops_pct_change" for all the objects in `slide_data.features`. 

The mismatch prevents the visualization from showing up. `slide_meta.attributes.primary.field` has to be changed to "stops_pct_change" so that it matches the value in the properties object.

**Pull request merged**
