### PR TITLE
correct primary.field for rout_change_meta

### PR DESCRIPTION
**Pull request by nam20485**
Fix for #125

### CODE REVIEW

**Comment by nam20485** [comment]
Thanks Ed! Brian... approve and merge? :)

**Comment by znmeb** [comment]
go for it!

**Comment by BrianHGrant** [comment]
Merged to staging, feel free to merge to master when you are ready @nam20485

**Comment by nam20485** [comment]
I wish I could- it'd be easier if I didn't have to inundate you with a boatload of all these minor changes for the sandbox.

But, you guys have protected branch merging turned on so I am stuck relying on you guys to do the merge after you approve it. 

From my my perspective it just says "waiting for approvals (2 necessary)". So for me to be able to handle these minor commits without your intervention you guys would have to remove the approval requirement under protected branch settings, or give me higher permission access so that I could override the protection.

I understand if you aren't comfortable with that, but if you are I can assure you that I would always take great care to test my changes, and only commit after ensuring that I didn't risk availability of the production backend. In short taking great care with what I commit and how I commit it. :) Also I don't commit non-trivial changes without your express approval first.

**Pull request merged**
